"""Add ai_insights and ai_similar_destinations

Revision ID: 1c9a71bc2ed6
Revises: 
Create Date: 2026-06-02 17:45:53.023154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9a71bc2ed6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('ai_insights',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ai_similar_destinations',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('ai_similar_destinations',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ai_insights',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
